### Register a new user done
POST http://localhost:6767/auth/register
Content-Type: application/json

{
    "firstName": "Yashh",
    "lastName": "MEOW",
    "email": "yash@gmail.com",
    "password": "meow",
    "avatarUrl": "https://media.tenor.com/cRTQk6N_FxMAAAAe/swag-cat-swagbilli-cutecat-cats-cat-swag-ok-yooo-yo.png"
}

###

### Login done
POST http://localhost:6767/auth/login
Content-Type: application/json

{
    "email": "yash@gmail.com",
    "password": "meow"
}

###

### Logout done
GET http://localhost:6767/auth/logout

###

### Check auth status done
GET http://localhost:6767/auth/check-auth
###

GET http://https://localhost:
###